name: remix-app
type: nodejs:14

disk: 5000

web:
  commands:
    start: npm run start
  locations:
    '/':
      allow: true
      scripts: false
      passthru: true

mounts:
  'prisma/data':
    source: local
    source_path: 'data'

hooks:
  build: |
    npm install
    npm run build
